### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by bafonso** [Kosta-Github/signals-cpp#7]
I applied your example to two classes I have and I am unable to have it compile in VS2013:

on this line, in the constructor, I get:
m_conns.connect(cameraBoy->valueChanged, this, &onValueChanged);

Error	2	error C2276: '&' : illegal operation on bound member function expression	C:\Users\bruno\Source\Repos\TrackingScope\ScopeTrackingFLTK\pcoEdgeAcquisition\Tracking.cpp	53	1	ScopeTrackingFLTK

**Comment by Kosta-Github** [comment]
Did you try to remove the & in front of onValueChanged?

**Comment by Kosta-Github** [comment]
no feedback; closing...
